name: CI/CD Backend Express

on:
  push:
    branches: [ "cicd" ] # Se déclenche au push sur la branche cicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v3

      - name: ⚙️ Configuration de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Mets la version que tu utilises

      - name: 🏗️ Installation et vérification (Build)
        run: |
          npm ci
          # npm run build # Décommente cette ligne si tu utilises TypeScript

      - name: 🧹 Nettoyer l'ancienne version sur le serveur
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/boatswain/api
            rm -rf src ia_models package*.json server.js prisma node_modules 2>/dev/null || true

      - name: 🚀 Déploiement des fichiers sur le serveur
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "src,ia_models,package.json,package-lock.json,server.js,prisma"
          target: "/var/www/boatswain/api"

      - name: 🔄 Redémarrage de l'API avec PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            bash -ic 'cd /var/www/boatswain/api && npm install --production && npm install -g pm2 && npx prisma migrate deploy && pm2 delete api-express 2>/dev/null; pm2 start server.js --name "api-express" && pm2 save'
            